### ISSUE TITLE
Dynamic routing take 1

### ISSUE THREAD

**Issue by tailhook** [swindon-rs/swindon#12]
As the step one we just fetch addresses from external source:

```
http-destinations:
  my-application:
    addresses: !JsonRequest verwalter/v1/schedule?key=data.roles.my-application.all_backends
  verwalter:
    addresses:
    - localhost:8379
```

More comprehensive settings might look like:
```
htttp-destinations:
  my-application:
    addresses: !JsonRequest
      url: verwalter/v1/schedule?key=data.roles.my-application.all_backends
      refresh-interval: 10
```

Technically, as we support changing addresses on the fly anyway this should be relatively easy to implement.

/cc @popravich
