### ISSUE TITLE
Config mixins

### ISSUE THREAD

**Issue by tailhook** [swindon-rs/swindon#45]
There is emerging pattern of doing like this:
```
handlers:
   proj1-x: ..
   proj1-y: ..
   proj2-x: ..
http-destinations:
  proj1-a: ..
  proj1-b: ..
  proj2-a: ..
session-pools:
  proj1-x: ..
  proj2-x: ..
```
And it's a good idea to put all pieces into `proj1.yaml` and `proj2.yaml`. 
So the proposed syntax is:
```
mixins:
  proj1: ./proj1.yaml
  proj2: ./proj2.yaml
```
Where files `proj*.yaml` contain handlers, destinations and session pool and we prefix all of them by `proj1` (the key in map above).

Notes:

1. Nothing for `routing` is proposed here
2. It's unclear if auto-prefixing is useful. Because usage of that destination and routes should not be prefixed (to allow linking them accross files)
